apiVersion: v1
kind: ServiceAccount
metadata:
  name: insecure-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: insecure-service-account-binding
subjects:
- kind: ServiceAccount
  name: insecure-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin  # This role gives full admin privileges
  apiGroup: rbac.authorization.k8s.io
